//addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.1")
//addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.4")
//addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.6")
//addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.5.2")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.1.0" )
